FROM mcr.microsoft.com/dotnet/core/sdk:2.1 AS build-env
WORKDIR /app

RUN mkdir ./AzureTableBackupRestore
RUN mkdir /app/data

COPY ./AzureTableBackupRestore/*.csproj ./AzureTableBackupRestore/
COPY ./AzureTableBackupRestore/*.cs ./AzureTableBackupRestore/

RUN dotnet publish AzureTableBackupRestore -c Release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:2.1
WORKDIR /app
COPY --from=build-env /app/AzureTableBackupRestore/out .
ENTRYPOINT ["dotnet", "AzureTableBackupRestore.dll"]